# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/hotstuff.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/hotstuff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/hotstuff.proto\x12\x08hotstuff\"*\n\x08Proposal\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\" \n\rBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x04Vote\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x05\x12\x0c\n\x04vote\x18\x02 \x01(\x08\"\x1f\n\x0cVoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32~\n\x08HotStuff\x12;\n\x0cProposeBlock\x12\x12.hotstuff.Proposal\x1a\x17.hotstuff.BlockResponse\x12\x35\n\x0bVoteOnBlock\x12\x0e.hotstuff.Vote\x1a\x16.hotstuff.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hotstuff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPOSAL']._serialized_start=34
  _globals['_PROPOSAL']._serialized_end=76
  _globals['_BLOCKRESPONSE']._serialized_start=78
  _globals['_BLOCKRESPONSE']._serialized_end=110
  _globals['_VOTE']._serialized_start=112
  _globals['_VOTE']._serialized_end=150
  _globals['_VOTERESPONSE']._serialized_start=152
  _globals['_VOTERESPONSE']._serialized_end=183
  _globals['_HOTSTUFF']._serialized_start=185
  _globals['_HOTSTUFF']._serialized_end=311
# @@protoc_insertion_point(module_scope)
