# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hotstuff_pb2 as proto_dot_hotstuff__pb2


GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/hotstuff_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotStuffStub(object):
    """Define the HotStuff service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeBlock = channel.unary_unary(
                '/hotstuff.HotStuff/ProposeBlock',
                request_serializer=proto_dot_hotstuff__pb2.Proposal.SerializeToString,
                response_deserializer=proto_dot_hotstuff__pb2.BlockResponse.FromString,
                _registered_method=True)
        self.VoteOnBlock = channel.unary_unary(
                '/hotstuff.HotStuff/VoteOnBlock',
                request_serializer=proto_dot_hotstuff__pb2.Vote.SerializeToString,
                response_deserializer=proto_dot_hotstuff__pb2.VoteResponse.FromString,
                _registered_method=True)


class HotStuffServicer(object):
    """Define the HotStuff service
    """

    def ProposeBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteOnBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotStuffServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeBlock,
                    request_deserializer=proto_dot_hotstuff__pb2.Proposal.FromString,
                    response_serializer=proto_dot_hotstuff__pb2.BlockResponse.SerializeToString,
            ),
            'VoteOnBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteOnBlock,
                    request_deserializer=proto_dot_hotstuff__pb2.Vote.FromString,
                    response_serializer=proto_dot_hotstuff__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotstuff.HotStuff', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotstuff.HotStuff', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotStuff(object):
    """Define the HotStuff service
    """

    @staticmethod
    def ProposeBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotstuff.HotStuff/ProposeBlock',
            proto_dot_hotstuff__pb2.Proposal.SerializeToString,
            proto_dot_hotstuff__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoteOnBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotstuff.HotStuff/VoteOnBlock',
            proto_dot_hotstuff__pb2.Vote.SerializeToString,
            proto_dot_hotstuff__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
